name: Test, build, and deploy

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
    - name: npm install, build, and lint
      run: |
        npm install
        npm run build
        npm test
      env:
        CI: true
    - name: Cache Composer packages
      uses: actions/cache@v1
      with:
        path: vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
    - name: Composer install and lint
      run: |
        composer install
        composer test
